name: Release

on:
  workflow_dispatch: 

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Build
        run: go build -v -o hledger-lsp.exe ./cmd/hledger-lsp

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hledger-lsp  # Name of the artifact (default: 'artifact')
          path: hledger-lsp.exe # File, directory, or wildcard pattern
